apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm-plain

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - podmonitoring.yaml

commonLabels:
  poc: gemma-vllm-vs-llmd
