apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllm-gemma
  namespace: vllm-plain
spec:
  selector:
    matchLabels:
      app: vllm-gemma
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
