apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm
  namespace: vllm-plain
  annotations:
    # Replace ${PROJECT_ID} with `kustomize edit set annotation` or sed at apply-time.
    iam.gke.io/gcp-service-account: inference-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hf-token
  namespace: vllm-plain
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_ID/secrets/hf-token/versions/latest"
        path: "hf-token"
